# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/149697yabGWNdR7gY-aZzjDnVePoUKiA0
"""

pip install streamlit

import streamlit as st
import random

# --- 1. Music Data (YOUR EMBED LINKS) ---
# NOTE: Links should be YouTube embed URLs (https://www.youtube.com/embed/VIDEO_ID)
MUSIC_DATA = {
    # Suited for High Energy / Commuting / Work (NEW TRACKS ADDED HERE)
    "City Pop": [
        "https://www.youtube.com/embed/TBLZSXwfjbE",
        "https://www.youtube.com/embed/p9dRg8yQ2DY",
        # New tracks for Work/Commuting:
        "https://www.youtube.com/embed/219beSEfbqA",
        "https://www.youtube.com/embed/_Q8Ih2SW-TE",
    ],

    # Suited for Medium Focus / Cafe/Study
    "Jazz HipHop": [
        "https://www.youtube.com/embed/dtVwR4uMnfg",
        "https://www.youtube.com/embed/OIvGy0wM5_s",
    ],

    # Suited for Low Energy / Home
    "Ambient Jazz": [
        "https://www.youtube.com/embed/CfPxlb8-ZQ0",
        "https://www.youtube.com/embed/o26qoCYLdS8",
    ]
}

# --- 2. Core Recommendation Logic (Python Function) ---
def recommend_music(mood_score, location):
    """
    Returns a recommended music genre based on the mood score (1-10) and location key.
    Uses only City Pop, Jazz HipHop, and Ambient Jazz.
    """

    # A. Mood-based primary determination
    if mood_score >= 8:
        genre = "City Pop"
    elif mood_score >= 5:
        genre = "Jazz HipHop"
    else: # 1-4
        genre = "Ambient Jazz"

    # B. Location-based refinement (ADDED 'Work' LOGIC)
    if location == "Commuting":
        genre = "City Pop" if mood_score >= 5 else "Jazz HipHop"
    elif location == "Work":
        # Work needs energy and focus: lean towards City Pop or Jazz HipHop
        genre = "City Pop" if mood_score >= 8 else "Jazz HipHop"
    elif location == "Park/Outdoor":
        genre = "City Pop" if mood_score >= 6 else "Jazz HipHop"
    elif location == "Home":
        genre = "Ambient Jazz" if mood_score < 6 else "Jazz HipHop"

    return genre

# --- 3. Streamlit UI (Pure Python for UI/Style) ---

st.set_page_config(page_title="Holiday Jazz Jukebox", layout="wide")

# --- CUSTOM CSS FOR CHRISTMAS VIBE AND SNOWFALL ---
st.markdown("""
    <style>
    /* 1. Import Festive Fonts */
    @import url('https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&family=Roboto:wght@400&display=swap');

    /* 2. Christmas Color Palette and Global Style */
    .stApp {
        background-color: #284d3c; /* Christmas Deep Green */
        color: #ecf0f1; /* Light Text (Snow White) */
        font-family: 'Roboto', sans-serif;
    }
    h1, h2, h3 {
        color: #f1c40f; /* Gold/Yellow Headers */
        font-family: 'Dancing Script', cursive; /* Festive Script Font for Headers */
        text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);
    }
    /* Button Style (Christmas Red) */
    .stButton>button {
        background-color: #C0392B;
        color: #ecf0f1;
        border: 2px solid #f1c40f; /* Gold Border */
        transition: all 0.3s ease-in-out;
        font-weight: 700;
    }
    .stButton>button:hover {
        background-color: #e74c3c;
    }
    /* Success/Notification boxes */
    [data-testid="stNotification"] {
        border-left: 5px solid #f1c40f;
        background-color: rgba(192, 57, 43, 0.2);
    }

    /* 3. Snowfall Animation CSS Definition */
    @keyframes snowfall {
        0% {top: -10%;}
        100% {top: 100%;}
    }

    .snowflake {
        color: #ecf0f1;
        font-size: 1em;
        position: fixed;
        z-index: 9999;
        user-select: none;
        pointer-events: none;
        animation-name: snowfall;
        animation-timing-function: linear;
        animation-iteration-count: infinite;
    }

    /* Defining different speeds and positions for varied effect */
    .snowflake:nth-child(1) { left: 5%; font-size: 1.2em; animation-duration: 10s; animation-delay: 0s; }
    .snowflake:nth-child(2) { left: 15%; font-size: 0.8em; animation-duration: 15s; animation-delay: 2s; }
    .snowflake:nth-child(3) { left: 25%; font-size: 1.5em; animation-duration: 12s; animation-delay: 4s; }
    .snowflake:nth-child(4) { left: 40%; font-size: 1.0em; animation-duration: 18s; animation-delay: 6s; }
    .snowflake:nth-child(5) { left: 60%; font-size: 1.3em; animation-duration: 11s; animation-delay: 8s; }
    .snowflake:nth-child(6) { left: 80%; font-size: 0.9em; animation-duration: 16s; animation-delay: 10s; }
    </style>
""", unsafe_allow_html=True)

# --- SNOWFLAKE HTML INJECTION ---
st.markdown("""
    <div class="snowflake">❄️</div>
    <div class="snowflake">🎄</div>
    <div class="snowflake">✨</div>
    <div class="snowflake">❅</div>
    <div class="snowflake">❄️</div>
    <div class="snowflake">❅</div>
""", unsafe_allow_html=True)

# --- APP TITLE ---
st.title("🎄 Winter Vinyl Jukebox: Tune Your Holiday Vibe")
st.subheader("❄️ Your personal station for Lofi, City Pop, and Ambient Jazz.")

# --- UI Controls ---
col1, col2 = st.columns(2)

with col1:
    st.markdown("### 1. Capture the Moment's Energy 📸")
    st.markdown("---")

    # Selectbox for Mood (Creative Input)
    mood_vibe = st.selectbox(
        label="Which light defines your current feeling?",
        options=[
            "✨ Excited & Sparkling (High Energy)",
            "☕ Calm & Pondering (Medium Focus)",
            "☁️ Cozy & Lazy (Low Chill)"
        ],
        index=1,
        help="High Energy (8-10), Focus (5-7), Chill (1-4)"
    )

    # Convert Vibe choice to Mood Score for the recommendation function
    if "Excited" in mood_vibe:
        mood_score = 9
    elif "Calm" in mood_vibe:
        mood_score = 6
    else:
        mood_score = 3

    st.info(f"**Your Vibe:** {mood_vibe.split(' ')[0].replace('✨', '').replace('☕', '').replace('☁️', '').strip()}")


with col2:
    st.markdown("### 2. Where is Your Turntable Spinning? 📍")
    st.markdown("---")

    # Radio buttons for Location (Creative Input) - 'Work' added here
    location = st.radio(
        label="Select your current setting's atmosphere",
        options=(
            "🏠 By the Cozy Fireplace (Home)",
            "🚌 Drifting Through the City (Commuting)",
            "🏢 Going to Work (Work)", # NEW OPTION
            "🌲 Snowy Park / Outdoors",
            "📚 Quiet Study Corner (Cafe/Study)"
        ),
        index=0 # Default to Home
    )

    # Convert Location choice to a simple key for the recommendation function
    if "Fireplace" in location:
        location_key = "Home"
    elif "City" in location:
        location_key = "Commuting"
    elif "Work" in location: # NEW LOGIC
        location_key = "Work"
    elif "Park" in location:
        location_key = "Park/Outdoor"
    elif "Corner" in location:
        location_key = "Cafe/Study"
    else:
        location_key = "Home"

    st.info(f"**Your Scene:** {location.split(' ')[1].replace('🏠', '').replace('🚌', '').replace('🏢', '').replace('🌲', '').replace('📚', '').strip()}")

st.markdown("---")

# --- Music Recommendation Button ---
if st.button("🎁 Open Your Personalized Jazz Box"):
    # Trigger balloon effect for celebration
    st.balloons()

    # 1. Get the recommended genre
    recommended_genre = recommend_music(mood_score, location_key)

    # 2. Select a random track URL from that genre
    if recommended_genre in MUSIC_DATA and MUSIC_DATA[recommended_genre]:
        track_url = random.choice(MUSIC_DATA[recommended_genre])

        st.success(f"**Recommended Vibe:** {recommended_genre}!")
        st.markdown(f"**Enjoy this selection!**")

        # 3. Display the music player using an HTML Iframe
        iframe_html = f"""
            <iframe
                src="{track_url}"
                width="100%"
                height="400"
                frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen>
            </iframe>
        """
        st.markdown(iframe_html, unsafe_allow_html=True)
    else:
        st.error(f"Sorry, no tracks found for the recommended genre: {recommended_genre}. Please check MUSIC_DATA.")

st.markdown("---")
st.markdown("A project built with Streamlit & Python. From @Hakowxy9.")