# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/149697yabGWNdR7gY-aZzjDnVePoUKiA0
"""

pip install streamlit

import streamlit as st
import random

# --- 1. Music Data (YOUR LINKS) ---
# City Pop: 适合高能量/兴奋 (8-10分) 或通勤
# Jazz HipHop: 适合中性/思考 (5-7分) 或学习
# Ambient Jazz: 适合低能量/放松 (1-4分) 或在家/休息
MUSIC_DATA = {
    "City Pop": [
        "https://www.youtube.com/embed/TBLZSXwfjbE",
        "https://www.youtube.com/embed/p9dRg8yQ2DY",
    ],

    "Jazz HipHop": [
        "https://www.youtube.com/embed/dtVwR4uMnfg",
        "https://www.youtube.com/embed/OIvGy0wM5_s",
    ],

    "Ambient Jazz": [
        "https://www.youtube.com/embed/CfPxlb8-ZQ0",
        "https://www.youtube.com/embed/o26qoCYLdS8",
    ]
}

# --- 2. Core Recommendation Logic (Python Function) ---
def recommend_music(mood_score, location):
    """
    Returns a recommended music genre based on the mood score and location.
    """

    # A. Mood-based primary determination
    if mood_score >= 8:
        genre = "City Pop"
    elif mood_score >= 5:
        genre = "Jazz HipHop"
    else: # 1-4
        genre = "Ambient Jazz"

    # B. Location-based refinement
    if location == "Commuting":
        if mood_score < 5:
            genre = "Jazz HipHop"
        else:
            genre = "City Pop"
    elif location == "Park/Outdoor":
        if mood_score < 6:
            genre = "Jazz HipHop"
        else:
            genre = "City Pop"
    elif location == "Home":
        if mood_score < 6:
            genre = "Ambient Jazz"
        else:
            genre = "Jazz HipHop"

    return genre

# --- 3. Streamlit UI (Pure Python for UI/Style) ---

# Set page configuration (English)
st.set_page_config(page_title="Mood Jazz Jukebox", layout="wide")

# Custom CSS for jazz aesthetic (Deep Navy Blue, Creamy White, Gold)
st.markdown("""
    <style>
    .stApp {
        background-color: #1a1a2e; /* Deep Navy Blue */
        color: #e4e6c3; /* Creamy White text */
        font-family: 'Georgia', serif;
    }
    h1, h2, h3 {
        color: #f7b32b; /* Muted Gold/Amber */
    }
    .stSlider label, .stRadio label {
        color: #e4e6c3;
    }
    /* Style for the button */
    .stButton>button {
        background-color: #f7b32b;
        color: #1a1a2e;
        border-radius: 5px;
        padding: 10px 20px;
        border: none;
        font-weight: bold;
    }
    /* Streamlit Info/Success boxes */
    [data-testid="stNotification"] {
        border-left: 5px solid #f7b32b;
    }
    </style>
""", unsafe_allow_html=True)

st.title("🎧 Mood Jazz Jukebox: Find Your Rhythm")
st.subheader("Jazz, Lofi HipHop, City Pop — Personalized for Your Vibe.")

# --- UI Controls ---
col1, col2 = st.columns(2)

with col1:
    st.markdown("### 1. How's Your Mood Score?")
    # Slider for mood score (1 to 10)
    mood_score = st.slider(
        label="Select a score from 1 (Low Energy) to 10 (Excited)",
        min_value=1,
        max_value=10,
        value=5
    )
    st.info(f"Your Current Mood Score: **{mood_score} / 10**")

with col2:
    st.markdown("### 2. Where Are You Right Now?")
    # Radio buttons for location
    location = st.radio(
        label="Choose your current setting",
        options=("Home", "Commuting", "Park/Outdoor", "Cafe/Study"),
        index=0 # Default to Home
    )
    st.info(f"Your Location: **{location}**")

st.markdown("---")

# --- Music Recommendation Button ---
if st.button("🎵 Get My Personalized Jazz Track"):
    # 1. Get the recommended genre
    recommended_genre = recommend_music(mood_score, location)

    # 2. Select a random track URL from that genre
    if recommended_genre in MUSIC_DATA and MUSIC_DATA[recommended_genre]:
        track_url = random.choice(MUSIC_DATA[recommended_genre])

        st.success(f"**Recommended Genre:** {recommended_genre}")
        st.markdown(f"**Enjoy this selection!**")

        # 3. Display the music player using an HTML Iframe
        iframe_html = f"""
            <iframe
                src="{track_url}"
                width="100%"
                height="400"
                frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen>
            </iframe>
        """
        st.markdown(iframe_html, unsafe_allow_html=True)
    else:
        st.error(f"Sorry, no tracks found for the recommended genre: {recommended_genre}. Please check MUSIC_DATA.")

st.markdown("---")
st.markdown("A project built with Streamlit & Python.")